<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13236" started-at="2016-02-18T14:05:56Z" finished-at="2016-02-18T14:06:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13236" started-at="2016-02-18T14:05:56Z" finished-at="2016-02-18T14:06:09Z">
      <class name="test.TestOpenCloseGoogle">
        <test-method status="FAIL" signature="test()[pri:0, instance:test.TestOpenCloseGoogle@270421f5]" name="test" duration-ms="11897" started-at="2016-02-18T15:05:56Z" finished-at="2016-02-18T15:06:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[nije proslo]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nije proslo
	at org.testng.Assert.fail(Assert.java:94)
	at lib.util.Verification.verifyPageExists(Verification.java:18)
	at test.TestOpenCloseGoogle.test(TestOpenCloseGoogle.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.TestOpenCloseGoogle@270421f5]" name="tearDown" is-config="true" duration-ms="1323" started-at="2016-02-18T15:06:08Z" finished-at="2016-02-18T15:06:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.TestOpenCloseGoogle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
